#!/bin/bash
#Optimised for Dell Latitude, 240GB SSD, 8GB RAM. 

#TODO
#Add paritioning

#1. Format partitions
mkfs.vfat /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mkfs.ext4 /dev/sda3 -yes
mkfs.ext4 /dev/sda4 -yes 

#2. Mount paritions
mount /dev/sda3 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
mkdir /mnt/home
mount /dev/sda4 /mnt/home

#3. Install base
pacstrap /mnt base base-devel

# generate fstab
genfstab -p -U /mnt >> /mnt/etc/fstab

#Fetch second script
wget -L https://raw.githubusercontent.com/zombieramboz/arch_install/master/script2

# copy the second script
cp script /mnt/script2

#Delete old scripts
rm script*
