#!/bin/bash
#Optimised for Dell Latitude, 240GB SSD, 8GB RAM. 

#TODO
#Add paritioning

#1. Format partitions
echo formatting partitions--------------
mkfs.vfat /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mkfs.ext4 /dev/sda3 -yes
mkfs.ext4 /dev/sda4 -yes 

#2. Mount paritions
echo mounting partitions----------------
mount /dev/sda3 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
mkdir /mnt/home
mount /dev/sda4 /mnt/home

#3. Install base
echo installing base--------------------
pacstrap /mnt base base-devel

#Change root into the new system: 
echo chrooting into new system----------
#arch-0chroot /mnt

#Time zone
arch-chroot timedatectl set-timezone Europe/London 

#Set hostname
arch-chroot echo "127.0.1.1 localhost.localdomain ArchPc" >> /etc/hosts
arch-chroot echo ArchPc >> /etc/hostname

arch-chroot echo -ne '\007'
